version: "3"

services:
  namenode:
    image: hadoop-namenode:latest
    container_name: namenode
    hostname: namenode
    domainname: hadoop
    ports:
      - 8020:8020
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: hadoop-datanode:latest
    container_name: datanode
    hostname: datanode
    domainname: hadoop
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    env_file:
      - ./hadoop.env

networks:
  default:
    external:
      name: hadoop
volumes:
  hadoop_namenode:
  hadoop_datanode:
